Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -119,3 +119,22 @@ for i in $diff_output_dirs; do
 		exit 1
 	fi
 done
+
+# ensure that there's not a >100mb file in this checkin, which github won't allow
+CURRENT_DIR="$(pwd)"
+HAS_ERROR=""
+
+for file in $(git diff --cached --name-only | sort | uniq); do
+	file_size=$(du -m $CURRENT_DIR/$file | awk '{print $1}')
+	if [ "$file_size" -ge 100 ]; then
+		echo "$file is over 100MB."
+		HAS_ERROR="1"
+	fi
+done
+
+if [ "$HAS_ERROR" != "" ]; then
+    echo "Can't commit, fix errors first." >&2
+    exit 1
+fi
+
+done
