Update pre-commit

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -20,6 +20,23 @@ fi
 # Redirect output to stderr.
 exec 1>&2
 
+# ensure that there's not a >100mb file in this checkin, which github won't allow
+CURRENT_DIR="$(pwd)"
+HAS_ERROR=""
+
+for file in $(git diff --cached --name-only | sort | uniq); do
+	file_size=$(du -m $CURRENT_DIR/$file | awk '{print $1}')
+	if [ "$file_size" -ge 100 ]; then
+		echo "$file is over 100MB."
+		HAS_ERROR="1"
+	fi
+done
+
+if [ "$HAS_ERROR" != "" ]; then
+    echo "Can't commit, fix errors first." >&2
+    exit 1
+fi
+
 git diff --cached --name-only --diff-filter=A -z $against -- "$ASSETS_DIR" | while read -d $'\0' f; do
 	ext="${f##*.}"
 	base="${f%.*}"
@@ -100,12 +117,16 @@ raw_diff_output=`git diff --cached --word-diff=plain .gitignore | egrep  "\{\+.*
 # prepare two strings: on for directories and one for meta files
 for raw_entry in $raw_diff_output; do
 	# strip leading and trailing separator "{+" and "+}"
-	e=${raw_entry:2:$((${#raw_entry}-4))}
-	is_meta=$((`echo $e | egrep ".*meta" | wc -l`))
-	if [ $is_meta -eq 0 ]; then
-		diff_output_dirs="${diff_output_dirs} ${e}"
+	if ((${#raw_entry} <= 4)); then
+		continue
 	else
-		diff_output_metas="${diff_output_metas} ${e}"
+		e=${raw_entry:2:$((${#raw_entry}-4))}
+		is_meta=$((`echo $e | egrep ".*meta" | wc -l`))
+		if [ $is_meta -eq 0 ]; then
+			diff_output_dirs="${diff_output_dirs} ${e}"
+		else
+			diff_output_metas="${diff_output_metas} ${e}"
+		fi
 	fi
 done
 
@@ -113,28 +134,10 @@ done
 for i in $diff_output_dirs; do 
 	# meta file entries are often without directory, so strip the path
 	dir_name=`echo $i | egrep -o "/[^/]+$" | cut -d / -f 2`
+	echo $dir_name
 	has_meta_ignore=$((`echo $diff_output_metas | grep "$dir_name.meta" | wc -l`))
 	if [ ${has_meta_ignore} -eq 0 ]; then
 		echo "$dir_name found in .gitignore but not the corresponding meta file! Please add ${dir_name}.meta to .gitignore"
 		exit 1
 	fi
-done
-
-# ensure that there's not a >100mb file in this checkin, which github won't allow
-CURRENT_DIR="$(pwd)"
-HAS_ERROR=""
-
-for file in $(git diff --cached --name-only | sort | uniq); do
-	file_size=$(du -m $CURRENT_DIR/$file | awk '{print $1}')
-	if [ "$file_size" -ge 100 ]; then
-		echo "$file is over 100MB."
-		HAS_ERROR="1"
-	fi
-done
-
-if [ "$HAS_ERROR" != "" ]; then
-    echo "Can't commit, fix errors first." >&2
-    exit 1
-fi
-
 done
